//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KendoUIDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public int StateID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string Name { get; set; }
        public string StateCode { get; set; }
        public string Capital { get; set; }
        public string LargestCity { get; set; }
        public Nullable<System.DateTime> Retification { get; set; }
        public Nullable<int> Population { get; set; }
        public Nullable<int> Area { get; set; }
    }
}
